### ISSUE TITLE
useNativeDriver warning react-native 0.63.0

### ISSUE THREAD

**Issue by maystrenkoYurii** [shahen94/react-native-switch#83]
react-native-switch 2.0.0
<img width="534" alt="Снимок экрана 2020-07-13 в 14 46 40" src="https://user-images.githubusercontent.com/23016311/87301180-c6e46d00-c517-11ea-8058-b3e5c3f7ef98.png">

**Comment by FortalezaRN** [comment]
I think that npm not updated because the code was fixed
![image](https://user-images.githubusercontent.com/9269631/90997362-b653f780-e597-11ea-90e1-a34b4e67c8da.png)

**Comment by maystrenkoYurii** [comment]
@FortalezaRN after merge 8 days dassed. But npm not updated. How match long time watch?

**Comment by Escalion86** [comment]
same issue

**Comment by fededirocco34** [comment]
Same here, has not updated it yet?

**Comment by abourge** [comment]
I'm seeing this, too

**Comment by Escalion86** [comment]
I fixed problem by adding some code like this
> ![image](https://user-images.githubusercontent.com/9269631/90997362-b653f780-e597-11ea-90e1-a34b4e67c8da.png)

**Comment by jspizziri** [comment]
In the interest of not waiting, republished this package under our org: [`@5stones/react-native-switch`](https://www.npmjs.com/package/@5stones/react-native-switch)

Adding here in case anyone is looking for a patch for now. Please note, this is only intended to be used until this issue is fixed.

**Comment by raphaelpinel** [comment]
Still the same issue with React Native 0.63.3. The fix did not get until npm?

**Comment by junhoyeo** [comment]
Plz update this package. 🙏 We have been waiting for like, five months

**Comment by MatiSera** [comment]
I'm having the same warning
"react-native-switch": "^2.0.0",
"react-native": "0.63.3",

**Comment by daniel3303** [comment]
While the NPM package is not updated you can install the most recent version of this package using the following command:
`npm install git+https://github.com/shahen94/react-native-switch.git`

**Comment by josegiufrida** [comment]
`Animated.spring()` must also include `UseNativeDriver: false`

![react-native-switch-useNativeDriver](https://user-images.githubusercontent.com/35411802/105862242-54783d80-5fce-11eb-9daa-ded97add2ce2.png)

**Comment by yashu2001** [comment]
I really appreciate the maintainers for the amazing package but can someone please push this fix to npm

**Comment by colinmatthewlee** [comment]
Any updates on this fix to npm?

**Comment by vaibhav834** [comment]
> Any updates on this fix to npm?

still same issue.

**Comment by mashaalmemon** [comment]
@shahen94, thanks for your work on this package.

However this particular issue (which looks like requires a very small fix) hasn't moved for many months now. 

Is this project being maintained by yourself anymore? If you can potentially accept @jspizziri 's PR or perhaps fix the issue in your own way, it would be great. However, if you're not maintaining this project anymore please advise.
